create table if not exists public.players (id bigint generated by default as identity primary key,username text not null,username_key text not null unique,created_at timestamptz not null default now());alter table public.players enable row level security;drop policy if exists "players_insert_public" on public.players;create policy "players_insert_public" on public.players for insert to anon,authenticated with check (true);create or replace function public.suggest_username(requested_name text) returns text language plpgsql security definer set search_path=public as $$ declare base_name text;base_key text;candidate text;i integer; begin base_name:=btrim(regexp_replace(coalesce(requested_name,''),'\s+',' ','g'));base_key:=lower(base_name);if base_name='' then raise exception 'Nome vazio';end if;if not exists(select 1 from public.players where username_key=base_key) then return base_name;end if;for i in 1..99999 loop candidate:=base_name||'_'||i::text;if not exists(select 1 from public.players where username_key=lower(candidate)) then return candidate;end if;end loop;raise exception 'Nenhuma variação disponível até _99999';end $$;revoke all on function public.suggest_username(text) from public;grant execute on function public.suggest_username(text) to anon,authenticated;grant insert on table public.players to anon,authenticated;grant usage,select on sequence public.players_id_seq to anon,authenticated;

-- ============================================================
-- Libera o username quando o jogador apaga o progresso.
-- ============================================================
create or replace function public.release_username(requested_name text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  cleaned text;
  deleted_count integer;
begin
  cleaned := lower(
    btrim(
      regexp_replace(
        coalesce(requested_name, ''),
        '\s+',
        ' ',
        'g'
      )
    )
  );

  if cleaned = '' then
    return false;
  end if;

  delete from public.players
  where username_key = cleaned;

  get diagnostics deleted_count = row_count;

  return deleted_count > 0;
end;
$$;

revoke all on function public.release_username(text) from public;
grant execute on function public.release_username(text) to anon, authenticated;
