create table if not exists public.players (id bigint generated by default as identity primary key,username text not null,username_key text not null unique,created_at timestamptz not null default now());alter table public.players enable row level security;drop policy if exists "players_insert_public" on public.players;create policy "players_insert_public" on public.players for insert to anon,authenticated with check (true);create or replace function public.suggest_username(requested_name text) returns text language plpgsql security definer set search_path=public as $$ declare base_name text;base_key text;candidate text;i integer; begin base_name:=btrim(regexp_replace(coalesce(requested_name,''),'\s+',' ','g'));base_key:=lower(base_name);if base_name='' then raise exception 'Nome vazio';end if;if not exists(select 1 from public.players where username_key=base_key) then return base_name;end if;for i in 1..99999 loop candidate:=base_name||'_'||i::text;if not exists(select 1 from public.players where username_key=lower(candidate)) then return candidate;end if;end loop;raise exception 'Nenhuma variação disponível até _99999';end $$;revoke all on function public.suggest_username(text) from public;grant execute on function public.suggest_username(text) to anon,authenticated;grant insert on table public.players to anon,authenticated;grant usage,select on sequence public.players_id_seq to anon,authenticated;

-- ============================================================
-- Libera o username quando o jogador apaga o progresso.
-- ============================================================
create or replace function public.release_username(requested_name text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  cleaned text;
  deleted_count integer;
begin
  cleaned := lower(
    btrim(
      regexp_replace(
        coalesce(requested_name, ''),
        '\s+',
        ' ',
        'g'
      )
    )
  );

  if cleaned = '' then
    return false;
  end if;

  delete from public.players
  where username_key = cleaned;

  get diagnostics deleted_count = row_count;

  return deleted_count > 0;
end;
$$;

revoke all on function public.release_username(text) from public;
grant execute on function public.release_username(text) to anon, authenticated;


-- ============================================================
-- GLOBAL CHAT — LAST 1,000 MESSAGES
-- ============================================================

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  username text not null,
  username_key text not null,
  body text not null,
  created_at timestamptz not null default now(),
  constraint chat_message_body_length check (char_length(body) between 1 and 500)
);

create index if not exists chat_messages_created_at_idx
on public.chat_messages (created_at desc);

create index if not exists chat_messages_id_idx
on public.chat_messages (id desc);

alter table public.chat_messages enable row level security;

drop policy if exists "chat_read_public" on public.chat_messages;
create policy "chat_read_public"
on public.chat_messages
for select
to anon, authenticated
using (true);

drop policy if exists "chat_insert_public" on public.chat_messages;
create policy "chat_insert_public"
on public.chat_messages
for insert
to anon, authenticated
with check (
  char_length(body) between 1 and 500
  and char_length(username) between 1 and 30
  and char_length(username_key) between 1 and 30
);

grant select, insert on table public.chat_messages to anon, authenticated;
grant usage, select on sequence public.chat_messages_id_seq to anon, authenticated;

create or replace function public.prune_global_chat()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  cutoff_id bigint;
begin
  select id
    into cutoff_id
  from public.chat_messages
  order by id desc
  offset 999
  limit 1;

  if cutoff_id is not null then
    delete from public.chat_messages
    where id < cutoff_id;
  end if;

  return new;
end;
$$;

drop trigger if exists chat_keep_last_1000 on public.chat_messages;

create trigger chat_keep_last_1000
after insert on public.chat_messages
for each row
execute function public.prune_global_chat();


-- ============================================================
-- REALTIME — chat_messages
-- ============================================================
-- Adds chat_messages to Supabase Realtime only if needed.

do $$
begin
  if not exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) then
    execute 'create publication supabase_realtime';
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'chat_messages'
  ) then
    execute 'alter publication supabase_realtime add table public.chat_messages';
  end if;
end
$$;
